# Generated by Django 4.0.4 on 2022-04-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tags',
            field=models.ManyToManyField(blank=True, to='invoices.tag'),
        ),
    ]
